spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=poner_usuario_aqui
spring.datasource.password=poner_password_aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format_sql=true